# Generated by Django 2.0.2 on 2018-10-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgqa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triples',
            old_name='object_text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='triples',
            name='predicts_text',
        ),
        migrations.RemoveField(
            model_name='triples',
            name='subject_text',
        ),
    ]
